##### Q10: Produce a list of facilities with a total revenue less than 1000. The output of facility name and total revenue, sorted by revenue. Remember that there's a different cost for guests and members!

In [1]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """SELECT * FROM 
(SELECT name, SUM(cost) AS total_revenue FROM 
(SELECT f.name, 
CASE b.memid 
WHEN 0 THEN f.guestcost*b.slots 
ELSE f.membercost*b.slots 
END AS cost 
FROM Bookings AS b 
INNER JOIN Facilities AS f 
ON b.facid=f.facid) AS subqurey 
GROUP BY name) AS S2 
WHERE total_revenue<1000 
ORDER BY total_revenue; 
"""
        
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Table Tennis', 180)
('Snooker Table', 240)
('Pool Table', 270)

##### Q11: Produce a report of members and who recommended them in alphabetic surname,firstname order

In [2]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """SELECT Memb.surname, Memb.firstname, Memb.recommendedby AS recomender
    FROM Members AS Memb
LEFT JOIN Members AS recom 
ON Memb.recommendedby = recom.memid
WHERE Memb.recommendedby != 0
ORDER BY recom.surname, recom.firstname;
        """
        
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('GUEST', 'GUEST', '')
('Smith', 'Darren', '')
('Smith', 'Tracy', '')
('Rownam', 'Tim', '')
('Tracy', 'Burton', '')
('Farrell', 'Jemima', '')
('Farrell', 'David', '')
('Tupperware', 'Hyacinth', '')
('Smith', 'Darren', '')
('Sarwin', 'Ramnaresh', '15')
('Coplin', 'Joan', '16')
('Genting', 'Matthew', '5')
('Baker', 'Timothy', '13')
('Pinker', 'David', '13')
('Rumney', 'Henrietta', '20')
('Jones', 'Douglas', '11')
('Dare', 'Nancy', '4')
('Jones', 'David', '4')
('Hunt', 'John', '30')
('Boothe', 'Tim', '3')
('Joplette', 'Janice', '1')
('Butters', 'Gerald', '1')
('Owen', 'Charles', '1')
('Smith', 'Jack', '1')
('Mackenzie', 'Anna', '1')
('Worthington-Smyth', 'Henry', '2')
('Purview', 'Millicent', '2')
('Crumpet', 'Erica', '2')
('Baker', 'Anne', '9')
('Bader', 'Florence', '9')
('Stibbons', 'Ponder', '6')

###### Q12 Find the facilities with their usage by member, but not guests

In [3]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
      SELECT b.facid, COUNT( b.memid ) AS mem_usage, f.name
FROM (
SELECT facid, memid
FROM Bookings
WHERE memid !=0
) AS b
LEFT JOIN Facilities AS f ON b.facid = f.facid
GROUP BY b.facid;
        """
        
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 308, 'Tennis Court 1')
(1, 276, 'Tennis Court 2')
(2, 344, 'Badminton Court')
(3, 385, 'Table Tennis')
(4, 421, 'Massage Room 1')
(5, 27, 'Massage Room 2')
(6, 195, 'Squash Court')
(7, 421, 'Snooker Table')
(8, 783, 'Pool Table')

###### Q13:  Find the facilities usage by month, but not guests

In [4]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """SELECT strftime('%m',starttime) AS months, f.name ,SUM(b.slots) AS member_usage 
FROM Bookings b 
LEFT JOIN Facilities f 
ON b.facid=f.facid 
WHERE b.memid<>0 
GROUP BY name, months;

        """
        
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('07', 'Badminton Court', 165)
('08', 'Badminton Court', 414)
('09', 'Badminton Court', 507)
('07', 'Massage Room 1', 166)
('08', 'Massage Room 1', 316)
('09', 'Massage Room 1', 402)
('07', 'Massage Room 2', 8)
('08', 'Massage Room 2', 18)
('09', 'Massage Room 2', 28)
('07', 'Pool Table', 110)
('08', 'Pool Table', 303)
('09', 'Pool Table', 443)
('07', 'Snooker Table', 140)
('08', 'Snooker Table', 316)
('09', 'Snooker Table', 404)
('07', 'Squash Court', 50)
('08', 'Squash Court', 184)
('09', 'Squash Court', 184)
('07', 'Table Tennis', 98)
('08', 'Table Tennis', 296)
('09', 'Table Tennis', 400)
('07', 'Tennis Court 1', 201)
('08', 'Tennis Court 1', 339)
('09', 'Tennis Court 1', 417)
('07', 'Tennis Court 2', 123)
('08', 'Tennis Court 2', 345)
('09', 'Tennis Court 2', 414)